from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route('/sample', methods=['GET'])
def sample():
    return jsonify({
        "response": [
            {
                "sch_id": 11261146,
                "orig_key": 11261112,
                "res_id": 6941,
                "user_id": 84317,
                "made_by_user": 84315,
                "made_by_name": "Rohl, Heidi",
                "canc_by_user": 0,
                "canc_by_name": ", ",
                "auth_by": 84315,
                "ses_id": 23700249,
                "sch_start": "2019-01-21T16:00:00",
                "sec_start": 1548086400,
                "sec_end": 1548087636,
                "sch_end": "2019-01-21T16:20:36.393",
                "sch_made": "2019-01-21T16:04:06.920",
                "sch_reason": 1216,
                "purge": False,
                "cnx_user_id": 0,
                "destination": "Local (VFR only)",
                "rule_exempt": False,
                "sch_supercede": 0,
                "CATEGORY": "AIRPLANE",
                "N_NO": "1234D",
                "MODEL": "C172",
                "LOCATION": "",
                "NAME": "Joe Miller",
                "lastname": "Miller",
                "firstname": "Joe",
                "maint": False,
                "hmphone": "",
                "wrkphone": "",
                "cellphone": "",
                "email": "",
                "tag": 0,
                "sch_comment": "",
                "unconfirmed": 0,
                "postflight_done": 1,
                "postflight_systime": "2019-01-21T13:20:57.533"
            },
            {
                "sch_id": 11275183,
                "orig_key": 11275180,
                "res_id": 8954,
                "user_id": 84331,
                "made_by_user": 84315,
                "made_by_name": "Rohl, Heidi",
                "canc_by_user": 0,
                "canc_by_name": ", ",
                "auth_by": 84315,
                "ses_id": 23729027,
                "sch_start": "2019-01-28T07:30:00",
                "sec_start": 1548660600,
                "sec_end": 1548661740,
                "sch_end": "2019-01-28T07:49:00.520",
                "sch_made": "2019-01-28T07:46:09.593",
                "sch_reason": 1088,
                "purge": False,
                "cnx_user_id": 0,
                "destination": "123",
                "rule_exempt": False,
                "sch_supercede": 0,
                "CATEGORY": "AIRPLANE",
                "N_NO": "345SM",
                "MODEL": "C172",
                "LOCATION": "",
                "NAME": "Valerie Smith",
                "lastname": "Smith",
                "firstname": "Valerie",
                "maint": False,
                "hmphone": "",
                "wrkphone": "",
                "cellphone": "",
                "email": "",
                "tag": 0,
                "sch_comment": "",
                "unconfirmed": 0,
                "postflight_done": 1,
                "postflight_systime": "2019-01-28T04:49:15.347"
            },
            {
                "sch_id": 11386608,
                "orig_key": 11386608,
                "res_id": 10031,
                "user_id": 84317,
                "made_by_user": 84317,
                "made_by_name": "Miller, Joe",
                "canc_by_user": 0,
                "canc_by_name": ", ",
                "auth_by": 84317,
                "ses_id": 23977190,
                "sch_start": "2019-03-26T10:00:00",
                "sec_start": 1553594400,
                "sec_end": 1553601600,
                "sch_end": "2019-03-26T12:00:00",
                "sch_made": "2019-03-26T09:51:32.250",
                "sch_reason": 0,
                "purge": False,
                "cnx_user_id": 0,
                "destination": "",
                "rule_exempt": False,
                "sch_supercede": 0,
                "CATEGORY": "AIRPLANE",
                "N_NO": "N123GT",
                "MODEL": "BE-76",
                "LOCATION": "",
                "NAME": "Joe Miller",
                "lastname": "Miller",
                "firstname": "Joe",
                "maint": False,
                "hmphone": "",
                "wrkphone": "",
                "cellphone": "",
                "email": "",
                "tag": 0,
                "sch_comment": "",
                "unconfirmed": 0,
                "postflight_done": 1,
                "postflight_systime": "2019-05-06T08:51:36.120"
            }
        ]
    }
)

if __name__ == '__main__':
    app.run()